language: java
jdk: openjdk8

script:
  - mvn clean install
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash) -t 43721452-78f1-4fef-b8d0-030283e57736


cache:
  directories:
    - $HOME/.m2

deploy:
  -
    on:
      branch: release
    provider: bintray
    skip_cleanup: true
    file: target/bin/bintray.json
    user: nfrankel
    key: $BINTRAY_API_KEY
